kind: pipeline
type: docker
name: integration

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    commands: 
      - dotnet sonarscanner begin 
      /k:"easv-devops_WebLibraryAPI_AY2N_guzEVvRW2O60D6R" 
      /d:sonar.host.url="http://sonar.setgo.dk:9000"  
      /d:sonar.token="sqp_59017899ff0f0bb5cc98d8c6916932306e6f1de4"
      - dotnet build 
      - dotnet sonarscanner end /d:sonar.token="sqp_59017899ff0f0bb5cc98d8c6916932306e6f1de4"
